[options]
addons_path = C:\Users\swaru\OneDrive\Documents\odoo\odoo18\source\odoo\addons,
              C:\Users\swaru\OneDrive\Documents\odoo\odoo18\source\odoo\odoo\addons,
              C:\Users\swaru\OneDrive\Documents\odoo\odoo18\custom\odoo_practic_project


db_host = localhost
db_port = 5433
db_user = odoo_user
db_password = 2002
admin_passwd = 2002
db_name = hospital_db
xmlrpc_port = 2026
bin_path = C:\Program Files\wkhtmltopdf\bin